[package]
name = "kapestr"
version = "0.1.0"
edition = "2021"
[dependencies]
chrono = "0.4.38"
gio = "0.19.8"
gtk4 = "0.8.2"
gtk4-sys = "0.8.2"
lazy_static = "1.5.0"
nostr = "0.32.1"
nostr-sdk = "0.32.0"
regex = "1.10.5"
reqwest = "0.12.5"
tokio = { version = "1.x", features = ["full"] }

